config/routes.rb
Hangout::Application.routes.draw do

  root :to => "hangout_events#index"

  get "signup" => "users#new", :as => "signup"
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"

  get "home" => "welcome#home", :as => 'welcome'

  get "/invited" => "hangout_events#invited", :as => "invited"
  post "/invite_users" => "hangout_events#invite_users", :as => "invite_users"

  get "/events/:id/vote" => "events#vote", :as => "event_vote"
  post "/events/:id/add_comment" => "events#add_comment", :as => "event_comment"
  
  resources :sessions
  resources :users
  resources :event_comments  
  resources :events
  resources :hangout_events
  resources :messages

end

app/models/event.rb
class Event
  include Mongoid::Document
  field :name, type: String
  field :details, type: String
  field :location, type: String
  field :start_time, type: Time
  field :end_time, type: Time

  belongs_to :hangout_event
  embeds_many :event_votes
  embeds_many :event_comments

  def upvote_or_downvote(upvote_or_downvote, user_id)
    self.event_votes.each do |vote|
      if vote.user_id == user_id 
        if upvote_or_downvote == vote.up #user voted the same way
          vote.destroy
          return
        elsif upvote_or_downvote != vote.up #user changed their vote
          vote.destroy
          self.event_votes.create(up: upvote_or_downvote, user_id: user_id)
          return
        end
      end
    end
    #otherwise it is a new vote
    self.event_votes.create(up: upvote_or_downvote, user_id: user_id)
  end

  def num_upvotes
    return self.num_upvotes_or_downvotes(true)
  end

  def num_downvotes
    return self.num_upvotes_or_downvotes(false)
  end

  #validate upvote and downvotes one per user
  def num_upvotes_or_downvotes(upvote_or_downvote)
    num_upvotes = 0
    self.event_votes.each do |vote|
      if vote.up == true
        num_upvotes += 1
      end
    end

    if (upvote_or_downvote)
      return num_upvotes
    else
      return self.event_votes.count - num_upvotes
    end
  end

  def add_comment(text, user_id)
    self.event_comments.create(text: text, timestamp: DateTime.now, user_id: user_id)
  end

  def upvotes_by
    users = []
    self.event_votes.each do |vote|
      if vote.up == true
        users.push(User.find(vote.user_id))
      end
    end
    return users
  end

  def downvotes_by
    users = []
    self.event_votes.each do |vote|
      if vote.up == false
        users.push(User.find(vote.user_id))
      end
    end
    return users
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :vote]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    redirect_to HangoutEvent.find(@event.hangout_event_id)
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.hangout_event_id = params[:hangout_id]

    respond_to do |format|
      if @event.save
        format.html { redirect_to HangoutEvent.find(@event.hangout_event_id), notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  # put this code in the model of the correct one
  def vote
    respond_to do |format|
      vote = params[:vote]
      if vote == "like"
        @event.upvote_or_downvote(true, session[:user_id])
      else
        @event.upvote_or_downvote(false, session[:user_id])
      end
      format.html { redirect_to @event }
      format.js   {}
    end
  end

  def add_comment
    @event = Event.find(params[:event_id])
    comment_text = params[:text]
    @event.add_comment(comment_text, session[:user_id])
    redirect_to HangoutEvent.find(@event.hangout_event_id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :details, :location, :start_time, :end_time)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_field :details %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.text_field :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.text_field :end_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Back to Hangout', @event %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Details</th>
      <th>Location</th>
      <th>Start time</th>
      <th>End time</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.details %></td>
        <td><%= event.location %></td>
        <td><%= event.start_time %></td>
        <td><%= event.end_time %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= @event.name %></h3>
  </div>
  <div class="panel-body">
    <div class="likes_box pull-right">
      <%
        @liked_users = ""
        @disliked_users = ""
      %>
      <% @event.upvotes_by.each do |user| %>
        <% @liked_users << user.full_name + "<br />"%>
      <% end %>
      <% @event.downvotes_by.each do |user| %>
        <% @disliked_users << user.full_name + "<br />" %>
      <% end %>    
      <%= link_to image_tag("thumbs_up.png", :size => "20"), event_vote_path(@event, :vote => "like"), :remote => true, :class => "show-tooltip", :title => @liked_users, :data => {:toggle => 'show-tooltip', :html => 'true'} %><span id="event_upvotes_<%= @event.id %>"><%= @event.num_upvotes %></span>

      <br />
      <%= link_to image_tag("thumbs_down.png", :size => "20"), event_vote_path(@event, :vote => "dislike"), :remote => true, :class => "show-tooltip", :title => @disliked_users, :data => {:toggle => 'show-tooltip', :html => 'true'} %><span id="event_downvotes_<%= @event.id %>"><%= @event.num_downvotes %></span>
    </div>
    <div class="pull-right" style="clear: right; padding: 5px;">
      <%= button_to 'Edit', edit_event_path(@event), :method => :get, :class => 'btn btn-primary'  %>
    </div>

    <div>
      <strong>Details:</strong>
      <%= @event.details %>
    </div>

    <div>
      <strong>Location:</strong>
      <%= @event.location %>
    </div>

    <div>
      <strong>Start time:</strong>
      <%= @event.start_time %>
    </div>

    <div>
      <strong>End time:</strong>
      <%= @event.end_time %>
    </div>

    <p>
      <strong>Comments:</strong><br/>
      <% @event.event_comments.each do |comment|%>
        <span><%= User.find(comment.user_id).full_name %>: </span>
        <span><%= comment.text %></span><br/>
      <% end %> 

      <!-- Create a form with an absolute URL and put in routes then create the object -->
      <%= form_tag(event_comment_path) do %>
        <div class="field">
          <%= text_field_tag :text %>
        </div>
        <input name="event_id" type="hidden" value=<%= @event.id %> /> 
        <div class="actions">
          <%= submit_tag "Add Comment" %>
        </div>
      <% end %>

    </p>
  </div>
</div>

<script type="text/javascript">
  $('.show-tooltip').tooltip()
</script>

app/views/events/vote.js.erb
$('#event_upvotes_' + '<%= @event.id %>').html(<%= @event.num_upvotes %>);
$('#event_downvotes_' + '<%= @event.id %>').html(<%= @event.num_downvotes %>);