config/routes.rb
Hangout::Application.routes.draw do

  root :to => "hangout_events#index"

  get "signup" => "users#new", :as => "signup"
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"

  get "home" => "welcome#home", :as => 'welcome'

  get "/invited" => "hangout_events#invited", :as => "invited"
  post "/invite_users" => "hangout_events#invite_users", :as => "invite_users"

  get "/events/:id/vote" => "events#vote", :as => "event_vote"
  post "/events/:id/add_comment" => "events#add_comment", :as => "event_comment"
  
  resources :sessions
  resources :users
  resources :event_comments  
  resources :events
  resources :hangout_events
  resources :messages

end

app/models/event_comment.rb
class EventComment
  include Mongoid::Document
  field :text, type: String
  field :timestamp, type: DateTime

  embedded_in :event
  belongs_to :user
end

app/controllers/event_comments_controller.rb
class EventCommentsController < ApplicationController
  before_action :set_event_comment, only: [:show, :edit, :update, :destroy]

  # GET /event_comments
  # GET /event_comments.json
  def index
    @event_comments = EventComment.all
  end

  # GET /event_comments/1
  # GET /event_comments/1.json
  def show
  end

  # GET /event_comments/new
  def new
    @event_comment = EventComment.new
  end

  # GET /event_comments/1/edit
  def edit
  end

  # POST /event_comments
  # POST /event_comments.json
  def create
    @event_comment = EventComment.new(event_comment_params)

    respond_to do |format|
      if @event_comment.save
        format.html { redirect_to @event_comment, notice: 'Event comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event_comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @event_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_comments/1
  # PATCH/PUT /event_comments/1.json
  def update
    respond_to do |format|
      if @event_comment.update(event_comment_params)
        format.html { redirect_to @event_comment, notice: 'Event comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_comments/1
  # DELETE /event_comments/1.json
  def destroy
    @event_comment.destroy
    respond_to do |format|
      format.html { redirect_to event_comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_comment
      @event_comment = EventComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_comment_params
      params.require(:event_comment).permit(:text, :timestamp)
    end
end

app/helpers/event_comments_helper.rb
module EventCommentsHelper
end

app/views/event_comments/_form.html.erb
<%= form_for(@event_comment) do |f| %>
  <% if @event_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event_comment.errors.count, "error") %> prohibited this event_comment from being saved:</h2>

      <ul>
      <% @event_comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :timestamp %><br>
    <%= f.text_field :timestamp %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/event_comments/edit.html.erb
<h1>Editing event_comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @event_comment %> |
<%= link_to 'Back', event_comments_path %>

app/views/event_comments/index.html.erb
<h1>Listing event_comments</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Timestamp</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @event_comments.each do |event_comment| %>
      <tr>
        <td><%= event_comment.text %></td>
        <td><%= event_comment.timestamp %></td>
        <td><%= link_to 'Show', event_comment %></td>
        <td><%= link_to 'Edit', edit_event_comment_path(event_comment) %></td>
        <td><%= link_to 'Destroy', event_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event comment', new_event_comment_path %>

app/views/event_comments/new.html.erb
<h1>New event_comment</h1>

<%= render 'form' %>

<%= link_to 'Back', event_comments_path %>

app/views/event_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @event_comment.text %>
</p>

<p>
  <strong>Timestamp:</strong>
  <%= @event_comment.timestamp %>
</p>

<%= link_to 'Edit', edit_event_comment_path(@event_comment) %> |
<%= link_to 'Back', event_comments_path %>